### ISSUE TITLE
Device  fails to be registered with HUB 

### ISSUE THREAD

**Issue by PSantosINFN** [plgd-dev/hub#891]
Using Device Provisioning Service, attempt to register a device in the HUB.
DPS Library (0.3) connects to DPS Service (0.8.3) and then Devices connects to the CoAP Gateway of the HUB (Bundle v2.7.11).
However, following messages appear in the Log:

{"L":"DEBUG","T":"2023-02-26T12:09:55.831809114Z","M":"cannot get deviceID from certificate: certificate is not set"}
{"L":"ERROR","T":"2023-02-26T12:09:55.831834003Z","M":"plgd/go-coap: tcp: 10.100.215.38:46842: cannot send CSM: cannot write to connection: tls: no cipher suite supported by both client and server"}

This situation happens about 1 in every 10 times with the Devices being used. What can be the root cause of this bug? 

Thank you.

**Comment by jkralik** [comment]
@PSantosINFN  What iotivity-lite revision do you use ?

Iotivity-lite had this issue which caused this error. The error occurs when the DTLS ciphers are set for the TCP connection to the hub.  It was fixed in commit: https://github.com/iotivity/iotivity-lite/commit/28f2b765e9af46a04c63a368d13591397578323f
